apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  SNIKKET_DOMAIN: example.com
  SNIKKET_ADMIN_EMAIL: admin@example.com
  SNIKKET_LETSENCRYPT_TOS_AGREE: Y
---
apiVersion: v1
kind: Pod
metadata:
  name: snikket
  labels:
    io.containers.autoupdate: image
spec:
  containers:
  - name: proxy
    image: docker.io/snikket/snikket-web-proxy:dev
    envFrom:
    - configMapRef:
        name: env
        optional: false
    volumeMounts:
    - name: data
      mountPath: /snikket
    - name: acme
      mountPath: /var/www/html/.well-known/acme-challenge
  - name: certs
    image: docker.io/snikket/snikket-cert-manager:dev
    envFrom:
    - configMapRef:
        name: env
        optional: false
    volumeMounts:
    - name: data
      mountPath: /snikket
    - name: acme
      mountPath: /var/www/.well-known/acme-challenge
  - name: portal
    image: docker.io/snikket/snikket-web-portal:dev
    envFrom:
    - configMapRef:
        name: env
        optional: false
  - name: server
    image: docker.io/snikket/snikket-server:dev
    envFrom:
    - configMapRef:
        name: env
        optional: false
    volumeMounts:
    - name: data
      mountPath: /snikket
  hostNetwork: true
  volumes:
  - name: data
    PersistentVolumeClaim:
      claimName: snikket-data
  - name: acme
    PersistentVolumeClaim:
      claimName: snikket-acme
